<a href="https://colab.research.google.com/github/HimanshuChhettri/PWSkills-Assignments/blob/NumPy-Assignment/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1) Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print("Data type of arr:", arr.dtype)

Data type of arr: int64


In [3]:
# 2) Given a NumPy array 'arr', check if its data type is float64.

import numpy as np
arr = np.array([1.5, 2.6, 3.7])
print("Is arr a float64 array?", arr.dtype == np.float64)

Is arr a float64 array? True


In [4]:
# 3) Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

import numpy as np
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)
print("Complex array:", arr)


Complex array: [1.+2.j 3.+4.j 5.+6.j]


In [6]:
# 4) Convert an existing NumPy array 'arr' of integers to float32 data type.

import numpy as np
arr = np.array([1, 2, 3])
arr_float32 = arr.astype(np.float32)
print("Converted to float32:", arr_float32)


Converted to float32: [1. 2. 3.]


In [7]:
# 5) Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

import numpy as np
arr = np.array([1.123456789, 2.234567890])
arr_float32 = arr.astype(np.float32)
print("Reduced decimal precision:", arr_float32)


Reduced decimal precision: [1.1234568 2.2345679]


In [9]:
# 6) Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

import numpy as np
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: int64


In [11]:
# 7)  Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

import numpy as np
def array_dimension(arr):
    dimension = len(arr.shape)
    return dimension
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)
print(dimension)

2


In [12]:
# 8) Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

import numpy as np
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)
print("Item size:", item_size)

Item size: 8


In [15]:
# 9) Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

import numpy as np
def array_strides(arr):
    strides = arr.strides
    return strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print(strides)

(24, 8)


In [17]:
# 10) Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

import numpy as np
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides
arr = np.array([1,2,3,4,5,6,7,8,9])
print(shape_stride_relationship(arr)[0])
print(shape_stride_relationship(arr)[1])

(9,)
(8,)


In [18]:
# 11) Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

import numpy as np
def create_zeros_array(n):
    zeros_array = np.zeros(n)
    return zeros_array
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)


[0. 0. 0. 0. 0.]


In [19]:
# 12)  Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

import numpy as np
def create_ones_matrix(rows, cols):
    ones_matrix = np.ones((rows, cols))
    return ones_matrix
rows = 3
cols = 4
result = create_ones_matrix(rows, cols)
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
# 13) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

import numpy as np
def generate_range_array(start, stop, step):
    range_array = np.arange(start, stop, step)
    return range_array
start = 1
stop = 10
step = 2
result = generate_range_array(start, stop, step)
print(result)


[1 3 5 7 9]


In [25]:
# 14) Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

import numpy as np
def generate_linear_space(start, stop, num):
    linspace_array = np.linspace(start, stop, num)
    return linspace_array
start = 1
stop = 10
num = 3
result = generate_linear_space(start, stop, num)
print(result)

[ 1.   5.5 10. ]


In [26]:
# 15) Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

import numpy as np
def create_identity_matrix(n):
    identity_matrix = np.eye(n)
    return identity_matrix
n = 4
result = create_identity_matrix(n)
print(result)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
# 16) Write a function that takes a Python list and converts it into a NumPy array.

import numpy as np
def list_to_numpy_array(python_list):
    numpy_array = np.array(python_list)
    return numpy_array

python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print(numpy_array)

[1 2 3 4 5]


In [29]:
# 17) Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data

import numpy as np
arr = np.array([1, 2, 3])
view_arr = arr.view()
print("Original array:", arr)
print("View array:", view_arr)

Original array: [1 2 3]
View array: [1 2 3]


In [33]:
# 18) Write a function that takes two NumPy arrays and concatenates them along a specified axis.

import numpy as np
def concatenate_arrays(arr1, arr2, axis=0):
    concatenated_array = np.concatenate((arr1, arr2), axis=axis)
    return concatenated_array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(arr1, arr2, axis=1)
print(concatenated_array)

[[1 2 5 6]
 [3 4 7 8]]


In [30]:
# 19) Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10]])
concatenated_array = np.concatenate((arr1, arr2), axis=1)
print("Horizontally concatenated array:")
print(concatenated_array)


Horizontally concatenated array:
[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


In [36]:
# 20) Write a function that vertically stacks multiple NumPy arrays given as a list

import numpy as np
def vertical_stack(array_list):
    stacked_array = np.vstack(array_list)
    return stacked_array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = vertical_stack([arr1, arr2])
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
# 21) Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

import numpy as np
def create_range_array(start, stop, step):
    return np.arange(start, stop+1, step)
arr1 = create_range_array(1, 10, 2)
print(arr1)

[1 3 5 7 9]


In [39]:
# 22) Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

import numpy as np
def generate_linspace_array():
    return np.linspace(0, 1, 10)
arr1 = generate_linspace_array()
print(arr1)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [45]:
# 23) Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

import numpy as np
def create_logspace_array():
    return np.logspace(1, 1000, 5)
arr1 = create_logspace_array()
print(arr1)

[1.00000000e+001 5.62341325e+250             inf             inf
             inf]


In [46]:
# 24) Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import numpy as np
import pandas as pd

# Create a NumPy array with 5 rows and 3 columns, filled with random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(data, columns=['Column 1', 'Column 2', 'Column 3'])

# Print the DataFrame
print(df)

   Column 1  Column 2  Column 3
0        38        27        96
1        95        56        72
2        83        14        77
3        53        60        59
4        44        39        54


In [47]:
# 25) Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):

  # Create a boolean mask for negative values in the specified column
  mask = df[column_name] < 0

  # Replace negative values with zeros using NumPy's where function
  df[column_name] = np.where(mask, 0, df[column_name])

  return df

# Example usage
data = {'column1': [1, -2, 3, -4, 5],
        'column2': [6, 7, -8, 9, 10]}
df = pd.DataFrame(data)

# Replace negative values in 'column1' with zeros
df = replace_negatives_with_zeros(df, 'column1')

print(df)

   column1  column2
0        1        6
1        0        7
2        3       -8
3        0        9
4        5       10


In [51]:
# 26. Access the 3rd element from the given NumPy array.

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print("Third element:", third_element)

Third element: 30


In [49]:
# 27) Retrieve the element at index (1, 2) from the 2D NumPy array.

import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]
print("Element at index (1, 2):", element)

Element at index (1, 2): 6


In [50]:
# 28) Using boolean indexing, extract elements greater than 5 from the given NumPy array.

import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
elements_greater_than_5 = arr[arr > 5]
print("Elements greater than 5:", elements_greater_than_5)

Elements greater than 5: [ 8 10  7]


In [53]:
# 29) Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]
print("Sliced array:", sliced_array)

Sliced array: [3 4 5 6]


In [54]:
# 30) Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[1:3, 1:3]
print("Sub-array:", sub_array)

Sub-array: [[5 6]
 [8 9]]


In [55]:
# 31) Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

import numpy as np
def extract_elements(array, indices):
    return array[indices]
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2]])
result = extract_elements(arr, indices)
print(result)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [56]:
# 32) Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

import numpy as np
def filter_elements(array, threshold):
    return array[array > threshold]
array = np.array([1, 2, 3, 4, 5])
threshold = 3
filtered_array = filter_elements(array, threshold)
print(filtered_array)

[4 5]


In [66]:
# 33) Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

import numpy as np
def extract_3d_elements(array, indices1, indices2, indices3):
    return array[indices1, indices2, indices3]
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print (array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [68]:
# 34) Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

import numpy as np
def filter_elements_multiple_conditions(array, condition1, condition2):
    return array[condition1 & condition2]
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition1 = (array % 2 == 0)
print (condition1)
condition2 = (array > 5)
print (condition2)
result = filter_elements_multiple_conditions(array, condition1, condition2)
print(result)

[False  True False  True False  True False  True False  True]
[False False False False False  True  True  True  True  True]
[ 6  8 10]


In [69]:
# 35) Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

import numpy as np
def extract_elements_row_col(array, row_indices, col_indices):
    return array[row_indices, col_indices]
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1])
col_indices = np.array([1, 2])
result = extract_elements_row_col(array, row_indices, col_indices)
print(result)

[2 6]


In [57]:
# 36) Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr + 5
print("Result:", result)

Result: [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [65]:
# 37) Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120]])
result = arr1.T * arr2
print(result)

[[ 10  20  30  40]
 [100 120 140 160]
 [270 300 330 360]]


In [77]:
# 38) Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

import numpy as np
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = arr1.T + arr2
print("Result:", result)

Result: [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [75]:
# 39) Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

import numpy as np
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[1, 2, 3]])
result = arr1 + arr2
print("Result:", result)

Result: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [78]:
# 40) Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4]])
result = arr1[:, :, np.newaxis] * arr2[:, np.newaxis, :]
print("Result:", result)

Result: [[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[12 16]
  [15 20]
  [18 24]]]


In [79]:
# 41) Calculate column-wise mean for the given array:

import numpy as  np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_means = np.mean(arr, axis=0)
print("Column means:", column_means)

Column means: [2.5 3.5 4.5]


In [80]:
# 42) Find maximum value in each row of the given array:

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print("Row maximums:", row_max)

Row maximums: [3 6]


In [81]:
# 43) For the given array, find indices of maximum value in each column.

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_max_indices = np.argmax(arr, axis=0)
print("Column max indices:", column_max_indices)

Column max indices: [1 1 1]


In [82]:
# 44) For the given array, apply custom function to calculate moving sum along rows.

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(row):
    return np.cumsum(row)
moving_sums = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print("Moving sums:", moving_sums)

Moving sums: [[ 1  3  6]
 [ 4  9 15]]


In [83]:
# 45) In the given array, check if all elements in each column are even.

import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
is_even = np.all(arr % 2 == 0, axis=0)
print("All elements in each column are even:", is_even)

All elements in each column are even: [False False False]


In [84]:
# 46) Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

import numpy as np
def reshape_matrix(arr, m, n):
    return arr.reshape(m, n)

arr = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
print(reshape_matrix(arr, m, n))

[[1 2 3]
 [4 5 6]]


In [87]:
# 47) Create a function that takes a matrix as input and returns the flattened array.

import numpy as np
def flatten_matrix(matrix):
    return matrix.flatten()

arr = np.array([1, 2, 3, 4, 5, 6])
flattened_arr = flatten_matrix(arr)
print(flattened_arr)

[1 2 3 4 5 6]


In [90]:
# 48) Write a function that concatenates two given arrays along a specified axis.

import numpy as np
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
result = concatenate_arrays(arr1, arr2, axis=0)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [89]:
# 49) Create a function that splits an array into multiple sub-arrays along a specified axis.

import numpy as np
def split_array(array, num_splits, axis):
    return np.split(array, num_splits, axis=axis)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(split_array(arr, 3, 0))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [91]:
# 50) Write a function that inserts and then deletes elements from a given array at specified indices.

import numpy as np
def insert_and_delete(array, indices_to_insert, values_to_insert, indices_to_delete):
    array = np.insert(array, indices_to_insert, values_to_insert)
    array = np.delete(array, indices_to_delete)
    return array

arr1 = np.array([1, 2, 3, 4, 5])
indices_to_insert = [1, 3]
values_to_insert = [10, 20]
indices_to_delete = [0, 2]
result = insert_and_delete(arr1, indices_to_insert, values_to_insert, indices_to_delete)
print(result)

[10  3 20  4  5]


In [93]:
# 51) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

import numpy as np
np.random.seed(42)
arr1 = np.random.randint(1, 100, size=10)
arr2 = np.arange(1, 11)
result = arr1 + arr2
print("Element-wise addition:", result)

Element-wise addition: [53 95 18 76 66 27 90 95 84 85]


In [94]:
# 52) Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

import numpy as np
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print("Element-wise subtraction:", result)

Element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [99]:
# 53) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

import numpy as np
np.random.seed(42)
arr1 = np.random.randint(1, 100, size=5)
arr2 = np.arange(1, 6)
result = arr1 * arr2
print("Element-wise multiplication:", result)

Element-wise multiplication: [ 52 186  45 288 305]


In [100]:
# 54) Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

import numpy as np
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2
print("Element-wise division:", result)

Element-wise division: [2. 2. 2. 2. 2.]


In [102]:
# 55) Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

import numpy as np
arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)
result = np.power(arr1, arr2)
print("Element-wise exponentiation:", result)

Element-wise exponentiation: [ 1 16 27 16  5]


In [103]:
# 56) Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

import numpy as np

def count_substring_occurrences(arr, substring):
  # Use NumPy's char.count method to count occurrences in each string
  counts = np.char.count(arr, substring)

  # Sum the counts to get the total occurrences
  total_occurrences = np.sum(counts)

  return total_occurrences

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

occurrences = count_substring_occurrences(arr, substring)
print("Number of occurrences of 'hello':", occurrences)

Number of occurrences of 'hello': 3


In [104]:
# 57) Write a function that extracts uppercase characters from a NumPy array of strings.

import numpy as np

def extract_uppercase_characters(arr):

  # Use np.char.upper to convert all characters to uppercase
  uppercase_arr = np.char.upper(arr)

  # Use np.char.isalpha and np.char.isupper to filter only uppercase letters
  uppercase_characters = uppercase_arr[np.char.isalpha(uppercase_arr) & np.char.isupper(uppercase_arr)]

  return uppercase_characters

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

uppercase_chars = extract_uppercase_characters(arr)
print(uppercase_chars)

['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [105]:
# 58) Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

import numpy as np

def replace_substring(arr, old_substring, new_substring):

  # Use np.char.replace to replace the substring in each string
  new_arr = np.char.replace(arr, old_substring, new_substring)

  return new_arr

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

new_array = replace_substring(arr, old_substring, new_substring)
print(new_array)

['orange' 'banana' 'grape' 'pineorange']


In [106]:
# 59) Write a function that concatenates strings in a NumPy array element-wise.

import numpy as np

def concatenate_strings(arr1, arr2):
  # Use np.char.add to concatenate corresponding elements
  concatenated_arr = np.char.add(arr1, arr2)

  return concatenated_arr

# Example usage
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

concatenated_arr = concatenate_strings(arr1, arr2)
print(concatenated_arr)

['HelloOpen' 'WorldAI']


In [108]:
# 60) Write a function that finds the length of the longest string in a NumPy array.

import numpy as np

def find_longest_string_length(arr):

  # Use np.char.len to get the length of each string
  string_lengths = np.char.str_len(arr)

  # Find the maximum length using np.max
  longest_string_length = np.max(string_lengths)

  return longest_string_length

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

longest_length = find_longest_string_length(arr)
print("Length of the longest string:", longest_length)

Length of the longest string: 9


In [111]:
# 61) Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

import numpy as np

# Create a dataset of 100 random integers
data = np.random.randint(1, 1001, size=100)

# Calculate mean, median, variance, and standard deviation
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 489.35
Median: 475.5
Variance: 83008.90749999999
Standard Deviation: 288.11266459494624


In [113]:
# 62) Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

import numpy as np
# Generate an array of 50 random numbers
data = np.random.randint(1, 101, size=50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

25th Percentile: 28.0
75th Percentile: 76.5


In [114]:
# 63) Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

import numpy as np
# Create two arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

# Calculate correlation coefficient
correlation = np.corrcoef(x, y)[0, 1]

print("Correlation Coefficient:", correlation)

Correlation Coefficient: 0.7745966692414834


In [115]:
# 64) Create two matrices and perform matrix multiplication using NumPy's dot function.

import numpy as np
# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Result of matrix multiplication:", result)

Result of matrix multiplication: [[19 22]
 [43 50]]


In [116]:
# 65) Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

import numpy as np
# Create an array of 50 integers
data = np.random.randint(10, 1001, size=50)

# Calculate percentiles and quartiles
percentile_10 = np.percentile(data, 10)
percentile_50 = np.median(data)
percentile_90 = np.percentile(data, 90)
quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

print("10th Percentile:", percentile_10)
print("Median:", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile:", quartile_1)
print("Third Quartile:", quartile_3)

10th Percentile: 239.4
Median: 510.5
90th Percentile: 836.3
First Quartile: 359.75
Third Quartile: 684.75


In [117]:
# 66) Create a NumPy array of integers and find the index of a specific element.

import numpy as np
# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Find the index of a specific element
index = np.where(arr == 30)[0][0]

print("Index of 30:", index)

Index of 30: 2


In [118]:
# 67) Generate a random NumPy array and sort it in ascending order.

import numpy as np
# Generate a random NumPy array
arr = np.random.randint(1, 101, size=10)

# Sort the array in ascending order
sorted_arr = np.sort(arr)

print("Sorted array:", sorted_arr)

Sorted array: [ 1  2  2 54 59 81 87 92 96 97]


In [119]:
# 68) Filter elements >20 in the given NumPy array.

import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements > 20
filtered_arr = arr[arr > 20]

print("Filtered array:", filtered_arr)

Filtered array: [25 42 30]


In [121]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.

import numpy as np
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

print("Filtered array:", filtered_arr)

Filtered array: [12 15]


In [122]:
# 70) Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 (inclusive)
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Filtered array:", filtered_arr)

Filtered array: [20 30 40]


In [124]:
# 71) For the given NumPy array, check its byte order using the dtype attribute byteorder.

import numpy as np
arr = np.array([1, 2, 3])

# Check byte order
byte_order = arr.dtype.byteorder

print("Byte order:", byte_order)

Byte order: =


In [125]:
# 72) For the given NumPy array, perform byte swapping in place using byteswap().

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

print("Swapped array:", arr)

Swapped array: [16777216 33554432 50331648]


In [127]:
# 73) For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().

import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying original array
swapped_arr = arr.newbyteorder()

print("Swapped array:", swapped_arr)

Swapped array: [16777216 33554432 50331648]


In [128]:
# 74) For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().

import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order if system is little-endian
if arr.dtype.byteorder == '<':
    swapped_arr = arr.newbyteorder('>')
else:
    swapped_arr = arr.newbyteorder('<')

print("Swapped array:", swapped_arr)

Swapped array: [1 2 3]


In [129]:
# 75) For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder.

import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
is_little_endian = arr.dtype.byteorder == '<'

if is_little_endian:
    print("Byte swapping is necessary for little-endian systems.")
else:
    print("Byte swapping is necessary for big-endian systems.")

Byte swapping is necessary for big-endian systems.


In [130]:
# 76) Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.

import numpy as np

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()

copy_arr[0] = 100
print("arr1:", arr1)
print("copy_arr:", copy_arr)

arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [131]:
# 77) Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.

import numpy as np
matrix = np.random.randint(1, 10, (3, 3))
view_slice = matrix[1:, 1:]

view_slice[0, 0] = 99
print("matrix:", matrix)

matrix: [[ 3  2  5]
 [ 6 99  4]
 [ 7  8  1]]


In [132]:
# 78) Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.

import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:, :]

view_b += 5
print("array_a:", array_a)

array_a: [[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [133]:
# 79) Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original orig_array.

import numpy as np
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 99
print("orig_array:", orig_array)

orig_array: [[99  2  3  4]
 [ 5  6  7  8]]


In [134]:
# 80) Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.

import numpy as np
data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5].copy()

data_copy[0] = 99
print("data:", data)

data: [[6 8 5 4]
 [2 6 6 1]
 [9 6 3 4]]


In [135]:
# 81) Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

import numpy as np
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

sum_matrix = A + B
diff_matrix = A - B

print("Sum matrix:", sum_matrix)
print("Difference matrix:", diff_matrix)

Sum matrix: [[12 10  5]
 [11  5 16]
 [13 11  8]]
Difference matrix: [[-4 -4  1]
 [-5  3 -2]
 [-5  7 -6]]


In [136]:
# 82) Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.

import numpy as np
C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))

product_matrix = np.dot(C, D)

print("Product matrix:", product_matrix)

Product matrix: [[66 78 36 42]
 [45 81 57 75]
 [19 23 11 13]]


In [137]:
# 83) Create a matrix E and find its transpose.

import numpy as np
E = np.random.randint(1, 10, (3, 4))

transpose_matrix = E.T

print("Transpose matrix:", transpose_matrix)

Transpose matrix: [[3 8 1]
 [4 1 8]
 [8 8 4]
 [6 4 6]]


In [138]:
# 84) Generate a square matrix F and compute its determinant.

import numpy as np
F = np.random.randint(1, 10, (3, 3))

determinant = np.linalg.det(F)

print("Determinant:", determinant)

Determinant: -60.000000000000036


In [139]:
# 85) Create a square matrix G and find its inverse.

import numpy as np
G = np.random.randint(1, 10, (3, 3))

try:
    inverse_matrix = np.linalg.inv(G)
    print("Inverse matrix:", inverse_matrix)
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")

Inverse matrix: [[-0.41025641  0.84615385  0.07692308]
 [-0.30769231  0.38461538  0.30769231]
 [ 0.48717949 -0.69230769 -0.15384615]]
